frase = str(input('Digite uma frase: ')).upper().strip()
#maius = frase.upper()
print(f'A letra "A" aparece {frase.count("A")} na sua frase')
print(f'A primeira letra "A" apareceu na posição {frase.find("A") + 1}')
print(f'A última letra "A" apareceu na posição {frase.rfind("A") + 1}')
